### ISSUE TITLE
Purpose of `included_codes.tsv` and `ComponentTree.tsv`?

### ISSUE THREAD

**Issue by sumeetchhetri** [loinc/comp-loinc#46]
These are some things you can export from: https://loinc.org/tree/

**Comment by joeflack4** [comment]
@sumeetchhetri I assume this is something we just want to know? Is there anything actionable within the codebase, like adding documentation to the readme o rin some comments?

@ShahimEssaid Do you know if we still have these in your implementation?

**Comment by joeflack4** [comment]
Shahim noticed: some parts are in the tree that are no longer in the release. Deprecated?

**Comment by joeflack4** [comment]
The latter: hierarchy export from that web app.
The former, included_codes, not sure what it is. Maybe a filter list. Maybe outdated.

We are migrating to a new codebase so this is no longer relevant.
